# Consider all the integer combinations of a^b for 2 <= a <= 5 and 2 <= b <= 5:

# if they are then placed in numerical order, with any repeats removed, we get the following
# sequence of 15 distinct terms:

# How many distinct terms are in the sequence generated by a^b for 2 < a < 100 and 2 < b < 100?

def power(a, b):
	return a ** b

distinctPowers = set([])

for a in range(2, 101):
	for b in range(2, 101):
		distinctPowers.add(power(a, b))

print len(distinctPowers)
