# Triangle, pentagonal, and hexagonal numbers are generated by
# the following formulae:
# 
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	Pn=n(3n-1)/2	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# 
# Find the next triangle number that is also pentagonal and hexagonal.

def getTriangle(n):
	return n*(n+1)/2

def getPentagonal(n):
	return n*(3*n-1)/2

def getHexagonal(n):
	return n*(2*n-1)

def Pentagonals(max_n):
	return [n*(3*n-1)/2 for n in range(1, max_n+1)]

def Hexagonals(max_n):
	return [n*(2*n-1) for n in range(1, max_n+1)]

pents = Pentagonals(1000000)
hexes = Hexagonals(1000000)

def isPentaHexa(num):
	global pents, hexes
	tri = getTriangle(num)
	if tri not in pents:
		return False
	if tri not in hexes:
		return False
	return True

found = False
n = 285
while not found:
	n += 1
	print n, pents[-1], hexes[-1]
	if isPentaHexa(n):
		print n, getTriangle(n)
		found = True

print
print "------------Done------------"



